#!/bin/bash
palindrome() {
	local arg="$1"
	local rarg=$(echo "$arg" | tr -d '[:space:]' | tr '[:upper:]' '[:lower:]')
	local len=${#rarg}
	local palindrome=true
	for (( i=0; i<len/2; i++ )); do
		if [[ "${rarg:$i:1}" != "${rarg:$((len - 1 - i)):1}" ]]; then
			return 1
		fi
	done
	return 0
}
if [ -z "$1" ]; then
	echo "Hmm, you haven't entered anything, try again">&2
	exit 1
fi
for arg in "$@"; do
	palindrome "$arg"
	if [[ $? -eq 0 ]]; then
		echo "'$arg' palindrome"
	else
		echo "'$arg' not palindrome"
	fi
done
exit 0
